server:
  port: 8082

spring:
  application:
    name: siteclone
  mvc:
    favicon:
      enabled: false

logging:
  level:
    root: INFO
    com.jiwu.aiseo.siteclone: DEBUG
    us.codecraft.webmagic: INFO